---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/4/17 10:11
---
---这里的 KEYS[1] 就是锁的key，这里的ARGV[1] 就是当前线程标识（都是作为参数传入）
if(redis.call('GET', KEYS[1]) == ARGV[1]) then ---获取锁中的标示，判断是否与当前线程标示一致
    -- 一致，则删除锁
    return redis.call('DEL', KEYS[1])
end
---不一致，则直接返回
return 0